### ISSUE TITLE
tslint.json conflict

### ISSUE THREAD

**Issue by ariasfernando** [benfoley/angular2-tag-input#2]
Hi! I've installed your plugin, and I'm having a problem with my tslint config. It seems that detects your tslint.json file and tries to include on linting routine, giving an error because angular2-tag-input doesn't have installed it's rules. I guess the package shouldn't have tslint.json file on production, it's only for dev purposes. Could you check it? Thanks!

**Comment by benfoley** [comment]
Hi, yes, looks like you're right. Check the issues over on https://github.com/rosslavery/angular2-tag-input.
